# Week 11 Lab: Linear Algebra with NumPy and SciPy
### Objective: Learn to use NumPy and SciPy for basic linear algebra operations.

In [10]:
import numpy as np
from scipy.linalg import solve

1. Create a 3×3 random matrix and compute its inverse using `numpy.linalg.inv()` .

In [3]:
matrix = np.random.rand(3, 3)
inverse_matrix = np.linalg.inv(matrix)
    
print("Original 3x3 Matrix:")
print(matrix)
print("\nInverse of the Matrix:")
print(inverse_matrix)

Original 3x3 Matrix:
[[0.72953468 0.74893778 0.26893924]
 [0.86920515 0.18262313 0.27788124]
 [0.83937656 0.46976966 0.87161381]]

Inverse of the Matrix:
[[-0.0944371   1.73609371 -0.52434923]
 [ 1.72923169 -1.3525177  -0.10236066]
 [-0.84105172 -0.94292286  1.70742177]]


2. Compute the dot product of two randomly generated vectors using `numpy.dot()` .

In [5]:
vector1 = np.random.rand(3)
vector2 = np.random.rand(3)

dot_product = np.dot(vector1, vector2)
    
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("\nDot Product:", dot_product)

Vector 1: [0.27085994 0.06135751 0.33404562]
Vector 2: [0.39931404 0.89602486 0.37833129]

Dot Product: 0.28951594736154673


3. Perform matrix-vector multiplication with NumPy.

In [7]:
matrix = np.random.rand(3, 3)
vector = np.random.rand(3)

result = np.dot(matrix, vector)
    
print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
print("\nResult of Matrix-Vector Multiplication:")
print(result)

Matrix:
[[0.97428333 0.43209745 0.84115207]
 [0.78203082 0.41747549 0.79518094]
 [0.02763361 0.94291781 0.83094786]]

Vector:
[0.21375953 0.04234875 0.57571466]

Result of Matrix-Vector Multiplication:
[0.71082471 0.64264343 0.5242272 ]


4. Solve a system of linear equations using `scipy.linalg.solve()` .

In [12]:
A = np.array([[2, -1, 1],
              [1,  3, 2],
              [1, -1, 2]])
    
b = np.array([3, 12, 5])
    
x = solve(A, b)
    
print("Solution to the system of equations:")
print(x)

Solution to the system of equations:
[0.91666667 1.75       2.91666667]


5. Compute the eigenvalues and eigenvectors of a given square matrix.

In [14]:
matrix = np.array([[4, -2, 1],
                   [1,  1, -1],
                   [3, -1, 2]])
    
eigenvalues, eigenvectors = np.linalg.eig(matrix)
    
print("Matrix:")
print(matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Matrix:
[[ 4 -2  1]
 [ 1  1 -1]
 [ 3 -1  2]]

Eigenvalues:
[5.+0.j 1.+1.j 1.-1.j]

Eigenvectors:
[[ 7.07106781e-01+0.j          3.00122524e-01+0.25724788j
   3.00122524e-01-0.25724788j]
 [-5.65783875e-17+0.j          7.28868987e-01+0.j
   7.28868987e-01-0.j        ]
 [ 7.07106781e-01+0.j          3.00122524e-01-0.47162111j
   3.00122524e-01+0.47162111j]]
